import React from 'react';
import Head from 'next/head';
import { useSelector, useDispatch } from 'react-redux';
import { decrement, increment, selectValue } from '../../slices/counterSlice';
import { multiplication, division } from '@/slices/multipleSlice';
import { RootState } from '@/store';

const HomePage = () => {
  const count = useSelector(selectValue);
  const dispatch = useDispatch();

  const multiValue = useSelector((state: RootState) => state.multiple.value);

  return (
    <>
      <Head>
        <title>redux-next-js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="mainContainer">
        <h1>The count value of {count}</h1>
        <div>
          <button style={{marginRight:'10px'}} onClick={() => dispatch(increment())}>Increment</button>
          <button onClick={() => dispatch(decrement())}>Decrement</button>
        </div>
        <br></br>
        <h1>The multiple value of {multiValue}</h1>
        <div>
          <button style={{marginRight:'10px'}} onClick={() => dispatch(multiplication())}>
            Multiplication
          </button>
          <button onClick={() => dispatch(division())}>Division</button>
        </div>
      </main>
    </>
  );
};

export default HomePage;
